name: Build Docker
on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        description: 'github token use to authentication'
        required: true
      TELEGRAM_CHAT_ID:
        description: 'telegram chat id'
        required: true
      TELEGRAM_BOT_TOKEN:
        description: 'telegram chat token'
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: Extract Version
        id: version_step
        run: |
          echo "version=${GITHUB_REF#$"refs/tags/"}" >> $GITHUB_OUTPUT
          echo "version_tag=ghcr.io/UpNext-SWAT-0/$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/"}" >> $GITHUB_OUTPUT

      - name: Prepare Registry Names
        id: read-docker-image-identifiers
        run: |
          echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./deployment/docker/Dockerfile
          tags: ${{ env.VERSION_TAG }}
          build-args: ${{ steps.version_step.outputs.version }}

      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_notification: true
          message: |
            ${{ github.actor }} Built Docker:
            Status: ${{ job.status }}
            Docker Image Version: ${{ steps.version_step.outputs.version }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}