
name: Build and Test
on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      TELEGRAM_CHAT_ID:
        description: 'telegram chat id'
        required: true
      TELEGRAM_BOT_TOKEN:
        description: 'telegram chat token'
        required: true
jobs:
  code-build:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check Go version
        run: go version

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2

      - name: Run tests
        run: go test -race -vet=off `go list ./... | grep -v test | grep -v vendor` # run all test expect test and vendor folder

      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_notification: true
          message: |
            ${{ github.actor }} Created Commit:
            Commit Message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Status: ${{ job.status }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}